package visitor;

import ast.*;

public interface Visitor {
	void visit(ASTNode astNode);
	void visit(ProgramNode programNode);
	void visit(DeclNode declNode);
	void visit(DeclListNode declListNode);
	void visit(IdListNode idListNode);
	void visit(IdDeclNode idDeclNode);
	void visit(IntTypeNode intTypeNode);
	void visit(FloatTypeNode floatTypeNode);
	void visit(CharTypeNode charTypeNode);
	void visit(ArrayTypeNode arrayTypeNode);
	void visit(DimNode dimNode);
	void visit(MinDimNode minDimNode);
	void visit(MaxDimNode maxDimNode);
	void visit(CmpStmtNode cmpStmtNode);
	void visit(StmtListNode stmtListNode);
	void visit(AssignmentNode assignmentNode);
	void visit(IdDefNode idDefNode);
	void visit(ExpNode expNode);
	void visit(OrNode orNode);
	void visit(MulNode mulNode);
	void visit(FactorNode factorNode);
	void visit(BracketNode bracketNode);
	void visit(ParenNode parenNode);
	void visit(ConstantNode constantNode);
	void visit(NotNode notNode);
	void visit(IdRefNode idRefNode);
	void visit(AndNode andNode);
	void visit(LTNode lTNode);
	void visit(GTNode gTNode);
	void visit(GENode gENode);
	void visit(NENode nENode);
	void visit(EQNode eQNode);
	void visit(AddNode addNode);
	void visit(SubNode subNode);
	void visit(ModNode modNode);
	void visit(LENode lENode);
	void visit(ProcInvNode procInv);
	void visit(ExpListNode expListNode);
	void visit(RetStmtNode retStmt);
	void visit(SubProgDeclNode subProgDeclNode);
	void visit(SubProgNode subProgNode);
	void visit(SubProgHeadNode subProgHead);
	void visit(SubProgTypeNode subProgTypeNode);
	void visit(ArgsNode argsNode);
	void visit(ParamListNode paramListNode);
	void visit(CaseStmtNode caseStmtNode);
	void visit(CasesNode casesNode);
	void visit(CaseElementNode caseElementNode);
	void visit(CaseLabelsNode caseLabelsNode);
	void visit(IoStmtNode ioStmtNode);
	void visit(ReadNode readNode);
	void visit(WriteNode writeNode);
	void visit(StringNode stringNode);
	void visit(IfStmtNode ifStmt);
	void visit(WhileStmtNode whileStmtNode);
	
}
